### ISSUE TITLE
How to fix this error?

### ISSUE THREAD

**Issue by Samir-OP** [SideProjectGuys/invite-manager-bot#179]
Unhandled Rejection at: Promise Promise {
  <rejected> Error: connect ECONNREFUSED 127.0.0.1:3306
      at PromisePool.query (/root/invite-manager-bot/node_modules/mysql2/promise.js:330:22)
      at DatabaseService.findManyOnSpecificShards (/root/invite-manager-bot/bin/framework/services/DatabaseService.js:119:32)
      at DatabaseService.getScheduledActionsForGuilds (/root/invite-manager-bot/bin/framework/services/DatabaseService.js:583:21)
      at SchedulerService.scheduleScheduledActions (/root/invite-manager-bot/bin/framework/services/Scheduler.js:78:44)
      at SchedulerService.onClientReady (/root/invite-manager-bot/bin/framework/services/Scheduler.js:24:20)
      at /root/invite-manager-bot/bin/client.js:169:68
      at Array.map (<anonymous>)
      at IMClient.onClientReady (/root/invite-manager-bot/bin/client.js:169:55)
      at IMClient.emit (/root/invite-manager-bot/node_modules/eventemitter3/index.js:180:35)
      at Shard.<anonymous> (/root/invite-manager-bot/node_modules/eris/lib/gateway/ShardManager.js:71:30)
      at Shard.emit (/root/invite-manager-bot/node_modules/eventemitter3/index.js:180:35)
      at Shard.checkReady (/root/invite-manager-bot/node_modules/eris/lib/gateway/Shard.js:1735:23)
      at Shard.restartGuildCreateTimeout (/root/invite-manager-bot/node_modules/eris/lib/gateway/Shard.js:1653:29)
      at Shard.wsEvent (/root/invite-manager-bot/node_modules/eris/lib/gateway/Shard.js:778:30)
      at Shard.onPacket (/root/invite-manager-bot/node_modules/eris/lib/gateway/Shard.js:1909:26)
      at Shard._onWSMessage (/root/invite-manager-bot/node_modules/eris/lib/gateway/Shard.js:1770:37) {
    code: 'ECONNREFUSED',
    errno: 'ECONNREFUSED',
    sqlState: undefined,
    sqlMessage: undefined
  }

**Comment by Samir-OP** [comment]
Fixed !
