### ISSUE TITLE
hi how can i fix this problem can someone help me pls

### ISSUE THREAD

**Issue by kpopdev** [SideProjectGuys/invite-manager-bot#183]
$ NPM start

> discord-invite-manager@9.8.0 start C:\Users\Administrator\Desktop\invite bot\invite-manager-bot
> cross-env NODE_ENV=dev node scripts/dev-run.js

> discord-invite-manager@9.8.0 build C:\Users\Administrator\Desktop\invite bot\invite-manager-bot
> tsc

Debugger listening on ws://127.0.0.1:19229/450edfbc-9563-4ae6-946a-49313ebc27a0
For help, see: https://nodejs.org/en/docs/inspector
internal/modules/cjs/loader.js:490
  throw new ERR_PACKAGE_PATH_NOT_EXPORTED(basePath, mappingKey);
  ^

Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './lib/rest/RequestHandler' is not defined by "exports" in C:\Users\Administrator\Desktop\invite bot\invite-manager-bot\node_modules\eris\package.json
    at applyExports (internal/modules/cjs/loader.js:490:9)
    at resolveExports (internal/modules/cjs/loader.js:506:23)
    at Function.Module._findPath (internal/modules/cjs/loader.js:634:31)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:952:27)
    at Function.Module._load (internal/modules/cjs/loader.js:841:27)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (C:\Users\Administrator\Desktop\invite bot\invite-manager-bot\bin\framework\RequestHandler.js:5:24)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10) {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
}

node ver LTS Version: 12.18.4

**Comment by chaun14** [comment]
#167
