### ISSUE TITLE
hi how to fix this error please.

### ISSUE THREAD

**Issue by kpopdev** [SideProjectGuys/invite-manager-bot#194]
DISCORD ERROR: TypeError: this.ws.removeEventListener is not a function
    at Shard.disconnect (C:\Users\Administrator\Desktop\invite-manager-bot-master\node_modules\eris\lib\gateway\Shard.js
:99:21)
    at Shard.onPacket (C:\Users\Administrator\Desktop\invite-manager-bot-master\node_modules\eris\lib\gateway\Shard.js:1
925:22)
    at Shard._onWSMessage (C:\Users\Administrator\Desktop\invite-manager-bot-master\node_modules\eris\lib\gateway\Shard.
js:1770:37)
    at native.client.group.onMessage (C:\Users\Administrator\Desktop\invite-manager-bot-master\node_modules\uws\uws.js:5
7:15)
EVENT(guildMemberAdd): 384522579379224578 Kpop Singing #EXO_SC_DESERVEBETTER 711335610970800168 jane <33#0001
DISCORD ERROR: { Error: 1001: Discord WebSocket requesting client reconnect.
    at Shard._onWSClose (C:\Users\Administrator\Desktop\invite-manager-bot-master\node_modules\eris\lib\gateway\Shard.js
:1842:23)
    at process.nextTick (C:\Users\Administrator\Desktop\invite-manager-bot-master\node_modules\uws\uws.js:64:19)
    at process._tickCallback (internal/process/next_tick.js:61:11) code: 1001 }
DISCORD DISCONNECT
Send message to RabbitMQ {
  "id": "status",
  "cmd": "STATUS",
  "state": "running",
  "startedAt": "2020-12-26T05:41:09.813Z",
  "gateway": false,
  "guilds": 117,
  "error": null,
  "tracking": {
    "pendingGuilds": 0,
    "initialPendingGuilds": 119
  },
  "music": {
    "connections": []
  },
  "cache": {
    "guilds": 117,
    "users": 38898,
    "channels": 4912,
    "roles": 8173,
    "ranks": 13,
    "settings": 82,
    "premium": 4,
    "permissions": 0,
    "strikes": 0,
    "punishments": 0,
    "inviteCodes": 12,
    "members": 0,
    "messages": 0
  },
  "metrics": {
    "wsEvents": 3682729,
    "wsWarnings": 5,
    "wsErrors": 14,
    "cmdProcessed": 5,
    "cmdErrors": 0,
    "httpRequests": [
      {
        "url": "GET:/gateway",
        "stats": {
          "total": 1,
          "succeeded": 1,
          "errors": 0
        }
      },
      {
        "url": "GET:/guilds/:id/invites",
        "stats": {
          "total": 299,
          "succeeded": 298,
          "errors": 0
        }
      },
      {
        "url": "GET:/guilds/:id/audit-logs",
        "stats": {
          "total": 108,
          "succeeded": 108,
          "errors": 0
        }
      },
      {
        "url": "GET:/guilds/:id/members/null",
        "stats": {
          "total": 69,
          "succeeded": 0,
          "errors": 69
        }
      },
      {
        "url": "POST:/channels/:id/messages",
        "stats": {
          "total": 48,
          "succeeded": 48,
          "errors": 0
        }
      },
      {
        "url": "PATCH:/channels/:id/messages/:id",
        "stats": {
          "total": 1,
          "succeeded": 1,
          "errors": 0
        }
      },
      {
        "url": "GET:/guilds/:id/members/:id",
        "stats": {
          "total": 10,
          "succeeded": 2,
          "errors": 8
        }
      },
      {
        "url": "POST:/users/@me/channels",
        "stats": {
          "total": 1,
          "succeeded": 1,
          "errors": 0
        }
      }
    ],
    "httpRequestsQueued": []
  }
}
DISCORD CONNECT
Send message to RabbitMQ {
  "id": "status",
  "cmd": "STATUS",
  "state": "running",
  "startedAt": "2020-12-26T05:41:09.813Z",
  "gateway": true,
  "guilds": 117,
  "error": null,
  "tracking": {
    "pendingGuilds": 0,
    "initialPendingGuilds": 119
  },
  "music": {
    "connections": []
  },
  "cache": {
    "guilds": 117,
    "users": 38898,
    "channels": 4912,
    "roles": 8173,
    "ranks": 13,
    "settings": 82,
    "premium": 4,
    "permissions": 0,
    "strikes": 0,
    "punishments": 0,
    "inviteCodes": 12,
    "members": 0,
    "messages": 0
  },
  "metrics": {
    "wsEvents": 3682729,
    "wsWarnings": 5,
    "wsErrors": 14,
    "cmdProcessed": 5,
    "cmdErrors": 0,
    "httpRequests": [
      {
        "url": "GET:/gateway",
        "stats": {
          "total": 1,
          "succeeded": 1,
          "errors": 0
        }
      },
      {
        "url": "GET:/guilds/:id/invites",
        "stats": {
          "total": 299,
          "succeeded": 298,
          "errors": 0
        }
      },
      {
        "url": "GET:/guilds/:id/audit-logs",
        "stats": {
          "total": 108,
          "succeeded": 108,
          "errors": 0
        }
      },
      {
        "url": "GET:/guilds/:id/members/null",
        "stats": {
          "total": 69,
          "succeeded": 0,
          "errors": 69
        }
      },
      {
        "url": "POST:/channels/:id/messages",
        "stats": {
          "total": 48,
          "succeeded": 48,
          "errors": 0
        }
      },
      {
        "url": "PATCH:/channels/:id/messages/:id",
        "stats": {
          "total": 1,
          "succeeded": 1,
          "errors": 0
        }
      },
      {
        "url": "GET:/guilds/:id/members/:id",
        "stats": {
          "total": 10,
          "succeeded": 2,
          "errors": 8
        }
      },
      {
        "url": "POST:/users/@me/channels",
        "stats": {
          "total": 1,
          "succeeded": 1,
          "errors": 0
        }
      }
    ],
    "httpRequestsQueued": []
  }
}

**Comment by chaun14** [comment]
Can you tell when that error happen?

**Comment by kpopdev** [comment]
USING AUDIT LOGS FOR 789540673593409577 IN 384522579379224578
EVENT(guildMemberAdd): 384522579379224578 Kpop Singing #EXO_SC_DESERVEBETTER 771513721591693324 Fenix025#3616
USING AUDIT LOGS FOR 771513721591693324 IN 384522579379224578
EVENT(guildMemberRemove): Kpop Singing #EXO_SC_DESERVEBETTER christmas vore 7906
EVENT(guildMemberAdd): 384522579379224578 Kpop Singing #EXO_SC_DESERVEBETTER 315461901033406474 spooky#0004
USING AUDIT LOGS FOR 315461901033406474 IN 384522579379224578
EVENT(guildMemberRemove): Kpop Singing #EXO_SC_DESERVEBETTER spooky 0004
EVENT(guildMemberRemove): Kpop Singing #EXO_SC_DESERVEBETTER Fenix025 3616
DISCORD ERROR: TypeError: this.ws.removeEventListener is not a function
    at Shard.disconnect (C:\Users\Administrator\Desktop\invite-manager-bot-master\node_modules\eris\lib\gateway\Shard.js
:99:21)
    at Shard.onPacket (C:\Users\Administrator\Desktop\invite-manager-bot-master\node_modules\eris\lib\gateway\Shard.js:1
925:22)
    at Shard._onWSMessage (C:\Users\Administrator\Desktop\invite-manager-bot-master\node_modules\eris\lib\gateway\Shard.
js:1770:37)
    at native.client.group.onMessage (C:\Users\Administrator\Desktop\invite-manager-bot-master\node_modules\uws\uws.js:5
7:15)
EVENT(guildMemberAdd): 384522579379224578 Kpop Singing #EXO_SC_DESERVEBETTER 727140329106571316 min-ue eun sang#8284
USING AUDIT LOGS FOR 727140329106571316 IN 384522579379224578
DISCORD ERROR: { Error: 1001: Discord WebSocket requesting client reconnect.
    at Shard._onWSClose (C:\Users\Administrator\Desktop\invite-manager-bot-master\node_modules\eris\lib\gateway\Shard.js
:1842:23)
    at process.nextTick (C:\Users\Administrator\Desktop\invite-manager-bot-master\node_modules\uws\uws.js:64:19)
    at process._tickCallback (internal/process/next_tick.js:61:11) code: 1001 }
DISCORD DISCONNECT
Send message to RabbitMQ {
  "id": "status",
  "cmd": "STATUS",
  "state": "running",
  "startedAt": "2020-12-26T05:41:09.813Z",
  "gateway": false,
  "guilds": 117,
  "error": null,
  "tracking": {
    "pendingGuilds": 0,
    "initialPendingGuilds": 119
  },
  "music": {
    "connections": []
  },
  "cache": {
    "guilds": 117,
    "users": 38913,
    "channels": 4909,
    "roles": 8174,
    "ranks": 15,
    "settings": 85,
    "premium": 4,
    "permissions": 0,
    "strikes": 0,
    "punishments": 0,
    "inviteCodes": 13,
    "members": 0,
    "messages": 0
  },
  "metrics": {
    "wsEvents": 4078764,
    "wsWarnings": 5,
    "wsErrors": 18,
    "cmdProcessed": 6,
    "cmdErrors": 0,
    "httpRequests": [
      {
        "url": "GET:/gateway",
        "stats": {
          "total": 1,
          "succeeded": 1,
          "errors": 0
        }
      },
      {
        "url": "GET:/guilds/:id/invites",
        "stats": {
          "total": 313,
          "succeeded": 313,
          "errors": 0
        }
      },
      {
        "url": "GET:/guilds/:id/audit-logs",
        "stats": {
          "total": 116,
          "succeeded": 115,
          "errors": 0
        }
      },
      {
        "url": "GET:/guilds/:id/members/null",
        "stats": {
          "total": 78,
          "succeeded": 0,
          "errors": 78
        }
      },
      {
        "url": "POST:/channels/:id/messages",
        "stats": {
          "total": 52,
          "succeeded": 52,
          "errors": 0
        }
      },
      {
        "url": "PATCH:/channels/:id/messages/:id",
        "stats": {
          "total": 2,
          "succeeded": 2,
          "errors": 0
        }
      },
      {
        "url": "GET:/guilds/:id/members/:id",
        "stats": {
          "total": 10,
          "succeeded": 2,
          "errors": 8
        }
      },
      {
        "url": "POST:/users/@me/channels",
        "stats": {
          "total": 1,
          "succeeded": 1,
          "errors": 0
        }
      }
    ],
    "httpRequestsQueued": []
  }
}
DISCORD CONNECT
Send message to RabbitMQ {
  "id": "status",
  "cmd": "STATUS",
  "state": "running",
  "startedAt": "2020-12-26T05:41:09.813Z",
  "gateway": true,
  "guilds": 117,
  "error": null,
  "tracking": {
    "pendingGuilds": 0,
    "initialPendingGuilds": 119
  },
  "music": {
    "connections": []
  },
  "cache": {
    "guilds": 117,
    "users": 38913,
    "channels": 4909,
    "roles": 8174,
    "ranks": 15,
    "settings": 85,
    "premium": 4,
    "permissions": 0,
    "strikes": 0,
    "punishments": 0,
    "inviteCodes": 13,
    "members": 0,
    "messages": 0
  },
  "metrics": {
    "wsEvents": 4078764,
    "wsWarnings": 5,
    "wsErrors": 18,
    "cmdProcessed": 6,
    "cmdErrors": 0,
    "httpRequests": [
      {
        "url": "GET:/gateway",
        "stats": {
          "total": 1,
          "succeeded": 1,
          "errors": 0
        }
      },
      {
        "url": "GET:/guilds/:id/invites",
        "stats": {
          "total": 313,
          "succeeded": 313,
          "errors": 0
        }
      },
      {
        "url": "GET:/guilds/:id/audit-logs",
        "stats": {
          "total": 116,
          "succeeded": 115,
          "errors": 0
        }
      },
      {
        "url": "GET:/guilds/:id/members/null",
        "stats": {
          "total": 78,
          "succeeded": 0,
          "errors": 78
        }
      },
      {
        "url": "POST:/channels/:id/messages",
        "stats": {
          "total": 52,
          "succeeded": 52,
          "errors": 0
        }
      },
      {
        "url": "PATCH:/channels/:id/messages/:id",
        "stats": {
          "total": 2,
          "succeeded": 2,
          "errors": 0
        }
      },
      {
        "url": "GET:/guilds/:id/members/:id",
        "stats": {
          "total": 10,
          "succeeded": 2,
          "errors": 8
        }
      },
      {
        "url": "POST:/users/@me/channels",
        "stats": {
          "total": 1,
          "succeeded": 1,
          "errors": 0
        }
      }
    ],
    "httpRequestsQueued": []
  }
}
BOT HAS ALREADY STARTED, IGNORING EXTRA READY EVENT
EVENT(guildMemberRemove): Twice . .︵︵ʚïɞ ᴢᴇʀᴏ ᴛᴡᴏ �� 5223
Could not find join for 765950349340049450 in 768097203323273218
EVENT(guildMemberRemove): Twice . .︵︵ʚïɞ ╰─-̗̀♡✎ La avani 8497
Could not find join for 759154543979790376 in 768097203323273218
EVENT(guildMemberRemove): Twice . .︵︵ʚïɞ Maknae 4826
EVENT(guildMemberRemove): Twice . .︵︵ʚïɞ Irene 7662
EVENT(guildMemberAdd): 384522579379224578 Kpop Singing #EXO_SC_DESERVEBETTER 792542125455048724 OsuIsLife#8660
EVENT(guildMemberRemove): Kpop Singing #EXO_SC_DESERVEBETTER abdul 8073
EVENT(guildMemberAdd): 786701296933404682 ҂ ⬪: kumoru. ୧ 791338408341405726 princessx#4864
EVENT(guildMemberAdd): 384522579379224578 Kpop Singing #EXO_SC_DESERVEBETTER 436976457638477825 7/11#7111
USING AUDIT LOGS FOR 436976457638477825 IN 384522579379224578
EVENT(guildMemberAdd): 384522579379224578 Kpop Singing #EXO_SC_DESERVEBETTER 714226774392963124 zyrafka#4232
USING AUDIT LOGS FOR 714226774392963124 IN 384522579379224578
EVENT(guildMemberAdd): 786701296933404682 ҂ ⬪: kumoru. ୧ 791095064813502495 beau³#6354
EVENT(guildMemberAdd): 789580285867589683 SIMP NATION 627550548907917312 festive roseyy#7124

bot is running good but after 2 hours or more i get that error and sometimes it broke the bot also how to fix this  

"url": "GET:/guilds/:id/members/null",
"stats": {
"total": 69,
"succeeded": 0,
"errors": 69

why im getting error ? what is this

**Comment by kpopdev** [comment]
if i use your repo will those error gone?

**Comment by chaun14** [comment]
idk. Maybe
I've update few dependencies, that may fix that

**Comment by SyntaxDragon** [comment]
Sounds like something changed maybe check what dependencies have changed and if updating/downgrading helps.
