### ISSUE TITLE
Error I am receiving on startup

### ISSUE THREAD

**Issue by VogueMist** [SideProjectGuys/invite-manager-bot#203]
Error: spawn node ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:248:19)
    at onErrorNT (internal/child_process.js:431:16)
    at processTicksAndRejections (internal/process/task_queues.js:83:17) {
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn node',
  path: 'node',
  spawnargs: [
    '--inspect=19229',
    './bin/bot.js',
    '--no-rabbitmq',
    'NzA0NjY5NjE5MjgxMTk5MTQ0.XqggxQ.9qci8VMpDrGquIKZTTopUh2zhic',
    '1',
    '1'
  ]
}

**Comment by chaun14** [comment]
You should install nodejs correctly before trying to setup the bot 🤔

**Comment by VogueMist** [comment]
![image](https://user-images.githubusercontent.com/48735695/114953053-78218600-9e4f-11eb-8c68-cacd1b8fb49b.png)


> You should install nodejs correctly before trying to setup the bot 🤔
