### ISSUE TITLE
Error Connecting to MySQL User

### ISSUE THREAD

**Issue by impressiveaustin** [SideProjectGuys/invite-manager-bot#210]
Hello. I am trying to selfhost his project on my own bot. I have installed NodeJS, cloned the repo, installed MySQL and created a user with the username "austin". I have also did 'npm install'. When I try to start the bot however, it gives me this error: Unhandled Rejection at: Promise Promise {
  <rejected> { Error: Access denied for user 'root'@'localhost'
      at PromisePool.query (/home/austin/invite-manager-bot/node_modules/mysql2/promise.js:330:22)
      at DatabaseService.findMany (/home/austin/invite-manager-bot/bin/framework/services/DatabaseService.js:87:35)
      at DatabaseService.getMusicNodes (/home/austin/invite-manager-bot/bin/framework/services/DatabaseService.js:568:21)
      at MusicService.loadMusicNodes (/home/austin/invite-manager-bot/bin/music/services/MusicService.js:48:43)
      at MusicService.onClientReady (/home/austin/invite-manager-bot/bin/music/services/MusicService.js:41:24)
      at Promise.all.Object.values.map (/home/austin/invite-manager-bot/bin/client.js:169:68)
      at Array.map (<anonymous>)
      at IMClient.onClientReady (/home/austin/invite-manager-bot/bin/client.js:169:55)
      at IMClient.emit (/home/austin/invite-manager-bot/node_modules/eventemitter3/index.js:180:35)
      at Shard.shard.on (/home/austin/invite-manager-bot/node_modules/eris/lib/gateway/ShardManager.js:71:30)
      at Shard.emit (/home/austin/invite-manager-bot/node_modules/eventemitter3/index.js:180:35)
      at Shard.checkReady (/home/austin/invite-manager-bot/node_modules/eris/lib/gateway/Shard.js:1735:23)
      at Shard.restartGuildCreateTimeout (/home/austin/invite-manager-bot/node_modules/eris/lib/gateway/Shard.js:1653:29)
      at Shard.wsEvent (/home/austin/invite-manager-bot/node_modules/eris/lib/gateway/Shard.js:778:30)
      at Shard.onPacket (/home/austin/invite-manager-bot/node_modules/eris/lib/gateway/Shard.js:1909:26)
      at Shard._onWSMessage (/home/austin/invite-manager-bot/node_modules/eris/lib/gateway/Shard.js:1770:37)
    message: 'Access denied for user \'root\'@\'localhost\'',
    code: 'ER_ACCESS_DENIED_NO_PASSWORD_ERROR',
    errno: 1698,
    sqlState: '28000',
    sqlMessage: 'Access denied for user \'root\'@\'localhost\'' } } reason: { Error: Access denied for user 'root'@'localhost'
    at PromisePool.query (/home/austin/invite-manager-bot/node_modules/mysql2/promise.js:330:22)
    at DatabaseService.findMany (/home/austin/invite-manager-bot/bin/framework/services/DatabaseService.js:87:35)
    at DatabaseService.getMusicNodes (/home/austin/invite-manager-bot/bin/framework/services/DatabaseService.js:568:21)
    at MusicService.loadMusicNodes (/home/austin/invite-manager-bot/bin/music/services/MusicService.js:48:43)
    at MusicService.onClientReady (/home/austin/invite-manager-bot/bin/music/services/MusicService.js:41:24)
    at Promise.all.Object.values.map (/home/austin/invite-manager-bot/bin/client.js:169:68)
    at Array.map (<anonymous>)
    at IMClient.onClientReady (/home/austin/invite-manager-bot/bin/client.js:169:55)
    at IMClient.emit (/home/austin/invite-manager-bot/node_modules/eventemitter3/index.js:180:35)
    at Shard.shard.on (/home/austin/invite-manager-bot/node_modules/eris/lib/gateway/ShardManager.js:71:30)
    at Shard.emit (/home/austin/invite-manager-bot/node_modules/eventemitter3/index.js:180:35)
    at Shard.checkReady (/home/austin/invite-manager-bot/node_modules/eris/lib/gateway/Shard.js:1735:23)
    at Shard.restartGuildCreateTimeout (/home/austin/invite-manager-bot/node_modules/eris/lib/gateway/Shard.js:1653:29)
    at Shard.wsEvent (/home/austin/invite-manager-bot/node_modules/eris/lib/gateway/Shard.js:778:30)
    at Shard.onPacket (/home/austin/invite-manager-bot/node_modules/eris/lib/gateway/Shard.js:1909:26)
    at Shard._onWSMessage (/home/austin/invite-manager-bot/node_modules/eris/lib/gateway/Shard.js:1770:37)
  message: 'Access denied for user \'root\'@\'localhost\'',
  code: 'ER_ACCESS_DENIED_NO_PASSWORD_ERROR',
  errno: 1698,
  sqlState: '28000',
  sqlMessage: 'Access denied for user \'root\'@\'localhost\'' }

How do I fix this?

**Comment by impressiveaustin** [comment]
By the way, I am using Ubuntu 20.04 LTS (SSH)

**Comment by impressiveaustin** [comment]
I have fixed the issue by changing the database username and password in the configure file.
