### ISSUE TITLE
MySQL Error

### ISSUE THREAD

**Issue by impressiveaustin** [SideProjectGuys/invite-manager-bot#211]
I get this error when I try to start the bot: Unhandled Rejection at: Promise Promise {
  <rejected> { Error: Unknown database 'im_0'
      at PromisePool.query (/home/austin/invite-manager-bot/node_modules/mysql2/promise.js:330:22)
      at DatabaseService.findMany (/home/austin/invite-manager-bot/bin/framework/services/DatabaseService.js:87:35)
      at DatabaseService.getMusicNodes (/home/austin/invite-manager-bot/bin/framework/services/DatabaseService.js:568:21)
      at MusicService.loadMusicNodes (/home/austin/invite-manager-bot/bin/music/services/MusicService.js:48:43)
      at MusicService.onClientReady (/home/austin/invite-manager-bot/bin/music/services/MusicService.js:41:24)
      at Promise.all.Object.values.map (/home/austin/invite-manager-bot/bin/client.js:169:68)
      at Array.map (<anonymous>)
      at IMClient.onClientReady (/home/austin/invite-manager-bot/bin/client.js:169:55)
      at IMClient.emit (/home/austin/invite-manager-bot/node_modules/eventemitter3/index.js:180:35)
      at Shard.shard.on (/home/austin/invite-manager-bot/node_modules/eris/lib/gateway/ShardManager.js:71:30)
      at Shard.emit (/home/austin/invite-manager-bot/node_modules/eventemitter3/index.js:180:35)
      at Shard.checkReady (/home/austin/invite-manager-bot/node_modules/eris/lib/gateway/Shard.js:1735:23)
      at Shard.restartGuildCreateTimeout (/home/austin/invite-manager-bot/node_modules/eris/lib/gateway/Shard.js:1653:29)
      at Shard.wsEvent (/home/austin/invite-manager-bot/node_modules/eris/lib/gateway/Shard.js:778:30)
      at Shard.onPacket (/home/austin/invite-manager-bot/node_modules/eris/lib/gateway/Shard.js:1909:26)
      at Shard._onWSMessage (/home/austin/invite-manager-bot/node_modules/eris/lib/gateway/Shard.js:1770:37)
    message: 'Unknown database \'im_0\'',
    code: 'ER_BAD_DB_ERROR',
    errno: 1049,
    sqlState: '42000',
    sqlMessage: 'Unknown database \'im_0\'' } } reason: { Error: Unknown database 'im_0'
    at PromisePool.query (/home/austin/invite-manager-bot/node_modules/mysql2/promise.js:330:22)
    at DatabaseService.findMany (/home/austin/invite-manager-bot/bin/framework/services/DatabaseService.js:87:35)
    at DatabaseService.getMusicNodes (/home/austin/invite-manager-bot/bin/framework/services/DatabaseService.js:568:21)
    at MusicService.loadMusicNodes (/home/austin/invite-manager-bot/bin/music/services/MusicService.js:48:43)
    at MusicService.onClientReady (/home/austin/invite-manager-bot/bin/music/services/MusicService.js:41:24)
    at Promise.all.Object.values.map (/home/austin/invite-manager-bot/bin/client.js:169:68)
    at Array.map (<anonymous>)
    at IMClient.onClientReady (/home/austin/invite-manager-bot/bin/client.js:169:55)
    at IMClient.emit (/home/austin/invite-manager-bot/node_modules/eventemitter3/index.js:180:35)
    at Shard.shard.on (/home/austin/invite-manager-bot/node_modules/eris/lib/gateway/ShardManager.js:71:30)
    at Shard.emit (/home/austin/invite-manager-bot/node_modules/eventemitter3/index.js:180:35)
    at Shard.checkReady (/home/austin/invite-manager-bot/node_modules/eris/lib/gateway/Shard.js:1735:23)
    at Shard.restartGuildCreateTimeout (/home/austin/invite-manager-bot/node_modules/eris/lib/gateway/Shard.js:1653:29)
    at Shard.wsEvent (/home/austin/invite-manager-bot/node_modules/eris/lib/gateway/Shard.js:778:30)
    at Shard.onPacket (/home/austin/invite-manager-bot/node_modules/eris/lib/gateway/Shard.js:1909:26)
    at Shard._onWSMessage (/home/austin/invite-manager-bot/node_modules/eris/lib/gateway/Shard.js:1770:37)
  message: 'Unknown database \'im_0\'',
  code: 'ER_BAD_DB_ERROR',
  errno: 1049,
  sqlState: '42000',
  sqlMessage: 'Unknown database \'im_0\'' }

How do I fix this issue (possibly with sudo mysql)

**Comment by impressiveaustin** [comment]
I think I may have found out how to fix it (CREATE DATABASE im_0;)

**Comment by impressiveaustin** [comment]
I created databases im_0 and im_1, now I'm getting this error: Unhandled Rejection at: Promise Promise {
  <rejected> { Error: Table 'im_1.scheduledActions' doesn't exist
      at PromisePool.query (/home/austin/invite-manager-bot/node_modules/mysql2/promise.js:330:22)
      at DatabaseService.findManyOnSpecificShards (/home/austin/invite-manager-bot/bin/framework/services/DatabaseService.js:119:32)
      at DatabaseService.getScheduledActionsForGuilds (/home/austin/invite-manager-bot/bin/framework/services/DatabaseService.js:583:21)
      at SchedulerService.scheduleScheduledActions (/home/austin/invite-manager-bot/bin/framework/services/Scheduler.js:78:44)
      at SchedulerService.onClientReady (/home/austin/invite-manager-bot/bin/framework/services/Scheduler.js:24:20)
      at Promise.all.Object.values.map (/home/austin/invite-manager-bot/bin/client.js:169:68)
      at Array.map (<anonymous>)
      at IMClient.onClientReady (/home/austin/invite-manager-bot/bin/client.js:169:55)
      at IMClient.emit (/home/austin/invite-manager-bot/node_modules/eventemitter3/index.js:180:35)
      at Shard.shard.on (/home/austin/invite-manager-bot/node_modules/eris/lib/gateway/ShardManager.js:71:30)
      at Shard.emit (/home/austin/invite-manager-bot/node_modules/eventemitter3/index.js:180:35)
      at Shard.checkReady (/home/austin/invite-manager-bot/node_modules/eris/lib/gateway/Shard.js:1735:23)
      at Shard.restartGuildCreateTimeout (/home/austin/invite-manager-bot/node_modules/eris/lib/gateway/Shard.js:1653:29)
      at Shard.wsEvent (/home/austin/invite-manager-bot/node_modules/eris/lib/gateway/Shard.js:778:30)
      at Shard.onPacket (/home/austin/invite-manager-bot/node_modules/eris/lib/gateway/Shard.js:1909:26)
      at Shard._onWSMessage (/home/austin/invite-manager-bot/node_modules/eris/lib/gateway/Shard.js:1770:37)
    message: 'Table \'im_1.scheduledActions\' doesn\'t exist',
    code: 'ER_NO_SUCH_TABLE',
    errno: 1146,
    sqlState: '42S02',
    sqlMessage: 'Table \'im_1.scheduledActions\' doesn\'t exist' } } reason: { Error: Table 'im_1.scheduledActions' doesn't exist
    at PromisePool.query (/home/austin/invite-manager-bot/node_modules/mysql2/promise.js:330:22)
    at DatabaseService.findManyOnSpecificShards (/home/austin/invite-manager-bot/bin/framework/services/DatabaseService.js:119:32)
    at DatabaseService.getScheduledActionsForGuilds (/home/austin/invite-manager-bot/bin/framework/services/DatabaseService.js:583:21)
    at SchedulerService.scheduleScheduledActions (/home/austin/invite-manager-bot/bin/framework/services/Scheduler.js:78:44)
    at SchedulerService.onClientReady (/home/austin/invite-manager-bot/bin/framework/services/Scheduler.js:24:20)
    at Promise.all.Object.values.map (/home/austin/invite-manager-bot/bin/client.js:169:68)
    at Array.map (<anonymous>)
    at IMClient.onClientReady (/home/austin/invite-manager-bot/bin/client.js:169:55)
    at IMClient.emit (/home/austin/invite-manager-bot/node_modules/eventemitter3/index.js:180:35)
    at Shard.shard.on (/home/austin/invite-manager-bot/node_modules/eris/lib/gateway/ShardManager.js:71:30)
    at Shard.emit (/home/austin/invite-manager-bot/node_modules/eventemitter3/index.js:180:35)
    at Shard.checkReady (/home/austin/invite-manager-bot/node_modules/eris/lib/gateway/Shard.js:1735:23)
    at Shard.restartGuildCreateTimeout (/home/austin/invite-manager-bot/node_modules/eris/lib/gateway/Shard.js:1653:29)
    at Shard.wsEvent (/home/austin/invite-manager-bot/node_modules/eris/lib/gateway/Shard.js:778:30)
    at Shard.onPacket (/home/austin/invite-manager-bot/node_modules/eris/lib/gateway/Shard.js:1909:26)
    at Shard._onWSMessage (/home/austin/invite-manager-bot/node_modules/eris/lib/gateway/Shard.js:1770:37)
  message: 'Table \'im_1.scheduledActions\' doesn\'t exist',
  code: 'ER_NO_SUCH_TABLE',
  errno: 1146,
  sqlState: '42S02',
  sqlMessage: 'Table \'im_1.scheduledActions\' doesn\'t exist' }

Help, thanks.

**Comment by impressiveaustin** [comment]
I might have figured out how. Do I import the database (/scripts/db/setup_dbx.sql) to im_0, im_1, or both, or one?

**Comment by impressiveaustin** [comment]
Wait, I think I figured it out.
